### ISSUE TITLE
External link 404

### ISSUE THREAD

**Issue by nitinraturi** [appknox/careers#29]
Hi team, in the below screenshot from [README.md](https://github.com/appknox/careers/blob/master/README.md), the URL is throwing a 404 error.

![image](https://github.com/appknox/careers/assets/20740761/d71ead2a-1f6b-48db-bfbd-7a507644e01d)

**Comment by nitinraturi** [comment]
Hi team, I looked online for the Appknox architecture blog and found this [link](https://www.appknox.com/blog/architecture-behind-appknox-inspired-by-sherlock) from the official blog.

I would be happy to create a pull request if the above link is valid.

**Comment by nitinraturi** [comment]
Hi team, opened a pull request [https://github.com/appknox/careers/pull/30](https://github.com/appknox/careers/pull/30).

Changes

- Updated the [old URL](https://dhilipsiva.com/2015/01/26/architecture-at-appknox.html) with the [new one](https://www.appknox.com/blog/architecture-behind-appknox-inspired-by-sherlock).

**Comment by subho007** [comment]
Thanks for the PR 🙂
