### ISSUE TITLE
No place for a guy with around 1 year experience/Fresher?

### ISSUE THREAD

**Issue by sssaurabhhh** [appknox/careers#9]
I have been working in Python since last one year or you may say since starting of my career. Is there any vacancy for a guy like me? Please find my resume attached. Thanks!
[SAURABH SINGH.pdf](https://github.com/appknox/careers/files/1013175/SAURABH.SINGH.pdf)

**Comment by dhilipsiva** [comment]
@sssaurabhhh Sorry.Not at this point in time. Maybe in the future.
